### ISSUE TITLE
Documentation improvement request: what makes this different from regular taky?

### ISSUE THREAD

**Issue by SeawardDread** [skadakar/taky-itak#2]
It would be really helpful to understand at a high level (and maybe just a couple of bullets?) what makes this different from the current taky release to make it more compatible with itak (e.g. client zip formatting?)

**Comment by skadakar** [comment]
When itak was release nobody had support for making packages so it was a hacked together script to get that easily made for people. Now taky supports creating the itak package natively, so that is used now. 

There is no difference on the software now from regular taky, except it is containerized and you have prefilled sensible defaults and it creates the atak and itak certs and uploads them for you.

The target audience is all the people who wanted to play with itak and had next to none technical skill to setup a server themselves. 

For production or any serious use setting it up yourself is better.
